### ISSUE TITLE
DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp-sw#48]
I get this exception occasionally for the amp.dev serviceworker. I'm not 100% sure how to reproduce this. Loading the page -> clearing cache in DevTools -> reloading a few times sometimes triggers it. 

```
amp-sw.js:1 Uncaught (in promise) DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at https://cdn.ampproject.org/sw/amp-sw.js:1:8225
    at new Promise (<anonymous>)
    at r.transaction (https://cdn.ampproject.org/sw/amp-sw.js:1:8188)
    at async r._call (https://cdn.ampproject.org/sw/amp-sw.js:1:8591)
    at async r.put (https://cdn.ampproject.org/sw/amp-sw.js:1:7118)
    at async i.setTimestamp (https://cdn.ampproject.org/sw/amp-sw.js:1:9212)
    at async y.updateTimestamp (https://cdn.ampproject.org/sw/amp-sw.js:1:11953)
    at async i.cacheDidUpdate (https://cdn.ampproject.org/sw/amp-sw.js:1:14642)
    at async Object.put (https://cdn.ampproject.org/sw/amp-sw.js:1:17694)
```

**Comment by westonruter** [comment]
I've experienced this serveral times (months ago) when testing Workbox in the PWA plugin for WordPress. I think it's a browser issue, where after clearing browser data it sometimes takes IndexDB to become available again. That's just what I assume is going on.
